window._env_ = {
  API_URL: "${API_URL}",
  OIDC_AUTHORITY: "${OIDC_AUTHORITY}",
  OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}",
  OIDC_REDIRECT_URI: "${OIDC_REDIRECT_URI}",
  OIDC_POST_LOGOUT_REDIRECT_URI: "${OIDC_POST_LOGOUT_REDIRECT_URI}",
  OIDC_SCOPE: "${OIDC_SCOPE}"
};